### ISSUE TITLE
assert 'detection' in self.models

### ISSUE THREAD

**Issue by maiphong0411** [vuongminh1907/ComfyUI_ZenID#2]
I am following readme but I got an error at ZenID FaceSwap node. 
error:     assert 'detection' in self.models
AssertionError
insightface/app/face_analysis.py", line 43, in __init__
![image](https://github.com/user-attachments/assets/d91b6014-d0b9-418b-ac56-b5a8d484b6b3)

**Comment by maiphong0411** [comment]
I have another question, when swaping face, do I need to mask the face (the same as image example in readme)

**Comment by vuongminh1907** [comment]
Hi @maiphong0411,
- Regarding your first question, I answered this issue from this link, you can take a look at [this](https://github.com/vuongminh1907/ComfyUI_ZenID/issues/1).
- Secondly, when swapping face, there are 2 ways:

1.  Don't pass the mask into the ZenID node. The model will automatically create a mask for you.
There is simply no need to connect the mask.

2. Provide your own drawn mask, then pass the mask into the node.

**Comment by maiphong0411** [comment]
@vuongminh1907 thank you vey much for your support. I have solved the problem
